name: pre-commit tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  # The specific pre-commit tests configurations are found in
  # the .pre-commit-config.yaml file at the root of the repository
  pre-commit:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0
    - uses: actions/setup-python@v2
    - uses: pre-commit/action@v2.0.3
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
